apps:
  - name: argo-rollouts
    env: platform
    namespace: argo-rollouts
    path: apps-infra/argo-rollouts
    syncWave: "-3"
    valuesFiles:
      - values.yaml

  - name: external-secrets
    env: platform
    namespace: external-secrets
    path: apps-infra/external-secrets
    syncWave: "-3"
    valuesFiles:
      - values.yaml

  - name: external-dns
    env: platform
    namespace: external-dns
    path: apps-infra/external-dns
    syncWave: "-3"
    valuesFiles:
      - values.yaml

  - name: qrify-web
    env: dev
    namespace: dev
    valuesFiles:
      - values.yaml
      - values.dev.yaml

  - name: qrify-web
    env: prod
    namespace: prod
    valuesFiles:
      - values.yaml
      - values.prod.yaml

  - name: qrify-web-api
    env: dev
    namespace: dev
    valuesFiles:
      - values.yaml
      - values.dev.yaml

  - name: qrify-web-api
    env: prod
    namespace: prod
    valuesFiles:
      - values.yaml
      - values.prod.yaml

  - name: qrify-portal
    env: dev
    namespace: dev
    valuesFiles:
      - values.yaml
      - values.dev.yaml

  - name: qrify-portal
    env: prod
    namespace: prod
    valuesFiles:
      - values.yaml
      - values.prod.yaml

  - name: prometheus-grafana
    env: dev
    namespace: dev
    valuesFiles:
      - values.yaml
      - values.dev.yaml

  - name: qrify-secrets
    env: dev
    namespace: dev
    syncWave: "-1"
    valuesFiles:
      - values.yaml
      - values.dev.yaml

  - name: qrify-secrets
    env: prod
    namespace: prod
    syncWave: "-1"
    valuesFiles:
      - values.yaml
      - values.prod.yaml

  - name: loki-stack
    env: dev
    namespace: logging
    path: apps/loki-stack
    valuesFiles:
      - values.yaml

  - name: eacds
    env: dev
    namespace: dev
    valuesFiles:
      - values.yaml
      - values.dev.yaml

  - name: eacds
    env: prod
    namespace: prod
    valuesFiles:
      - values.yaml
      - values.prod.yaml

  - name: testing
    env: dev
    namespace: dev
    valuesFiles:
      - values.yaml
      - values.dev.yaml

  - name: testing
    env: prod
    namespace: prod
    valuesFiles:
      - values.yaml
      - values.prod.yaml

  - name: test2
    env: dev
    namespace: dev
    valuesFiles:
      - values.yaml
      - values.dev.yaml

  - name: test2
    env: prod
    namespace: prod
    valuesFiles:
      - values.yaml
      - values.prod.yaml
