qrify-base:
  name: qrify-web-api
  deployment: true
  replicaCount: 2

  image:
    pullPolicy: IfNotPresent

  env:
    - name: PORT
      value: "8000"

  envSecrets:
    - aws-creds
    
  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: false
    className: "nginx"
    annotations: {}
    hosts: []
    tls: []

  resources: {}

  metrics:
    enabled: true
    path: /metrics
    interval: 15s


  livenessProbe: {}
  readinessProbe: {}



