qrify-base:
  environment: dev
  imageTag: 59b73ff3
  labels:
    test: 'true'
    app.kubernetes.io/instance: qrify-web-api-dev
    app.kubernetes.io/name: qrify-web-api-dev
    monitoring: enabled
  podLabels:
    app.kubernetes.io/instance: qrify-web-api-dev
    app.kubernetes.io/name: qrify-web-api-dev
    monitoring: enabled
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
