qrify-base:
  environment: prod
  imageTag: af2f3718
  labels:
    test: "true"
    app.kubernetes.io/instance: qrify-web-api-prod
    app.kubernetes.io/name: qrify-web-api-prod
    monitoring: enabled
  podLabels:
    app.kubernetes.io/instance: qrify-web-api-prod
    app.kubernetes.io/name: qrify-web-api-prod
    monitoring: enabled
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"



