qrify-base:
  name: qrify-web-api

  rollout:
    enabled: true
    activeService: qrify-web-api-active
    previewService: qrify-web-api-preview
    autoPromotionEnabled: true

  replicaCount: 2

  image:
    pullPolicy: IfNotPresent

  env:
    - name: PORT
      value: "8000"

  envSecrets:
    - aws-creds
    
  service:
    type: ClusterIP
    port: 8000

  ingress:
    enabled: false
    className: "nginx"
    annotations: {}
    hosts: []
    tls: []

  resources: {}

  metrics:
    enabled: true
    path: /metrics
    interval: 15s


  livenessProbe: {}
  readinessProbe:
    httpGet:
      path: /healthz
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3



