qrify-base:
  name: qrify-web-api
  ecrRegistry: "856096729725.dkr.ecr.us-east-2.amazonaws.com"

  rollout:
    enabled: true
    activeService: qrify-web-api-active
    previewService: qrify-web-api-preview
    autoPromotionEnabled: true

  replicaCount: 2

  image:
    pullPolicy: IfNotPresent

  serviceAccount:
    create: true
    name: qrify-web-api
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::856096729725:role/QRifyWebApiS3Role

  env:
    - name: PORT
      value: "8000"
    - name: S3_BUCKET_NAME
      value: "qrify-web-platform-storage"
    - name: AWS_REGION
      value: "us-east-2"
    - name: AWS_DEFAULT_REGION
      value: "us-east-2"

  service:
    type: ClusterIP
    port: 8000
    targetPort: 8000

  ingress:
    enabled: false
    className: "nginx"
    annotations: {}
    hosts: []
    tls: []

  resources: {}

  metrics:
    enabled: true
    path: /metrics
    interval: 15s

  livenessProbe: {}
  readinessProbe:
    httpGet:
      path: /health
      port: 8000
    initialDelaySeconds: 5
    periodSeconds: 10
    failureThreshold: 3
