apiVersion: v1
kind: Secret
metadata:
  name: qrify-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  name: qrify-helm
  type: helm
  url: https://qrify-platform.github.io/helm-charts