apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qrify-root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/QRify-platform/cluster-state
    targetRevision: HEAD
    path: app-of-apps
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
