apiVersion: v2
name: qrify-portal
description: Helm chart for QRify Portal
type: application
version: 0.0.1
dependencies:
  - name: qrify-base
    version: 0.0.19
    repository: https://Qrify-platform.github.io/helm-charts
  - name: qrify-secrets
    version: 0.0.4
    repository: https://Qrify-platform.github.io/helm-charts
