apiVersion: v2
name: qrify-secrets
description: Environment wrapper for qrify-secrets (External Secrets → AWS SM)
type: application
version: 0.0.1
dependencies:
  - name: qrify-secrets
    version: 0.0.1
    repository: https://Qrify-platform.github.io/helm-charts
