qrify-base:

  name: qrify-web
  deployment: true
  replicaCount: 2

  image:
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: 3000

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts: []
    tls: []

  env:
    - name:  NEXT_PUBLIC_API_BASE_URL
      value: "http://qrify-web-api:8000/generate-qr/"
  resources: {}

  livenessProbe: {}
  readinessProbe: {}