qrify-base:

  name: qrify-web
  deployment: true
  replicaCount: 2

  image:
    pullPolicy: IfNotPresent

  rollout:
    enabled: true
    activeService: qrify-web-active
    previewService: qrify-web-preview
    autoPromotionEnabled: true

  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts: []
    tls: []

  metrics:
    enabled: true
    path: /api/metrics
    interval: 15s

  env:
    - name:  NEXT_PUBLIC_API_BASE_URL
      value: "http://qrify-web-api.dev.svc.cluster.local:8000"
      
  resources: {}

  livenessProbe: {}
  readinessProbe:
      httpGet:
        path: /api/health
        port: 3000  
      initialDelaySeconds: 5
      periodSeconds: 5