qrify-base:
  environment: prod
  imageTag: 7df97f6e

  replicaCount: 3

  labels:
    test: "true"
    app.kubernetes.io/instance: qrify-web-prod
    app.kubernetes.io/name: qrify-web-prod
    monitoring: enabled
  podLabels:
    app.kubernetes.io/instance: qrify-web-prod
    app.kubernetes.io/name: qrify-web-prod
    monitoring: enabled
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/api/metrics"
    prometheus.io/port: "3000"
    
  ingress:
    enabled: true
    className: "nginx"
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: qrify-web.com
        paths:
          - path: /
            pathType: Prefix
    tls: {}
