qrify-base:
  environment: prod
  imageTag: 81a66178

  replicaCount: 3


  ingress:
    enabled: true
    className: "nginx"
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - host: qrify-web.com
        paths:
          - path: /
            pathType: Prefix
    tls: {}
