qrify-base:
  environment: prod
  imageTag: 6ba45af1

  replicaCount: 3

  rollout:
    autoPromotionEnabled: false
    
  labels:
    test: "true"
    app.kubernetes.io/instance: qrify-web-prod
    app.kubernetes.io/name: qrify-web-prod
    monitoring: enabled
  podLabels:
    app.kubernetes.io/instance: qrify-web-prod
    app.kubernetes.io/name: qrify-web-prod
    monitoring: enabled
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/api/metrics"
    prometheus.io/port: "3000"

  # Disabled until Route53 / custom domain is configured.
  ingress:
    enabled: false
    className: "nginx"
    annotations: {}
    hosts: []
    tls: []
