qrify-base:
  environment: dev
  imageTag: 03b37911

  replicaCount: 1

  labels:
    app.kubernetes.io/instance: eacds-dev
    app.kubernetes.io/name: eacds-dev
  podLabels:
    app.kubernetes.io/instance: eacds-dev
    app.kubernetes.io/name: eacds-dev
