apiVersion: v2
name: prometheus-grafana
description: A Helm umbrella chart for Prometheus and Grafana
type: application
version: 0.1.0

dependencies:
  - name: kube-prometheus-stack
    version: 56.6.0
    repository: https://prometheus-community.github.io/helm-charts
