qrify-base:
  environment: dev
  imageTag: "6dc31d70"
  replicaCount: 1

  labels:
    app.kubernetes.io/instance: test55-dev
    app.kubernetes.io/name: test55-dev
  podLabels:
    app.kubernetes.io/instance: test55-dev
    app.kubernetes.io/name: test55-dev
