apiVersion: v2
name: test2
description: Helm chart for test2 (scaffolded by QRify Portal)
type: application
version: 0.0.1
dependencies:
  - name: qrify-base
    version: 0.0.19
    repository: https://Qrify-platform.github.io/helm-charts
