qrify-base:
  environment: dev
  imageTag: 8c1dd2e1

  replicaCount: 1

  labels:
    app.kubernetes.io/instance: test2-dev
    app.kubernetes.io/name: test2-dev
  podLabels:
    app.kubernetes.io/instance: test2-dev
    app.kubernetes.io/name: test2-dev
