{{- range .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}-{{ .env }}
  namespace: argocd
  {{- if .syncWave }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncWave | quote }}
  {{- end }}
spec:
  project: default
  source:
    repoURL: {{ .customRepoUrl | default "https://github.com/QRify-platform/cluster-state" | quote }}
    targetRevision: HEAD
    path: {{ .path | default (printf "apps/%s" .name) }}
    {{- if .valuesFiles }}
    helm:
      dependencyUpdate: true
      valueFiles:
        {{- range .valuesFiles }}
        - {{ . | quote }}
        {{- end }}
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      {{- if eq .name "prometheus-grafana" }}
      - ServerSideApply=true
      {{- end }}
      {{- if eq .name "external-secrets" }}
      - ServerSideApply=true
      {{- end }}
---
{{- end }}
