{{- range .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}-{{ .env }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .customRepoUrl | default "https://github.com/QRify-platform/cluster-state" | quote }}
    targetRevision: HEAD
    path: {{ .path | default (printf "apps/%s" .name) }}
    helm:
      dependencyUpdate: true  
      {{- if .valuesFiles }}
      valueFiles:
        {{- range .valuesFiles }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
{{- end }}
