{{- range .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}-{{ .env }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/QRify-platform/cluster-state
    targetRevision: HEAD
    path: apps/{{ .name }}
    helm:
      dependencyUpdate: true
      valueFiles:
        {{- range .valuesFiles }}
        - {{ . | quote }}
        {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
{{- end }}
