name: Sync ArgoCD Root App

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  sync-argocd-root-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure kubectl for EKS
        uses: QRify-platform/github-actions/eks-kubeconfig@main
        with:
          aws-role-to-assume: ${{ secrets.AWS_EKS_ROLE_TO_ASSUME }}
          aws-region: us-east-2
          cluster-name: qrify-eks

      - name: Wait for Argo CD
        run: kubectl rollout status deployment/argocd-server -n argocd --timeout=120s

      - name: Apply root application
        run: |
          set -euo pipefail
          kubectl apply -f root-app.yaml
          kubectl -n argocd annotate application qrify-root-app \
            argocd.argoproj.io/refresh=hard --overwrite
          
